# specifying the services I'll be using:
services:
  # can be named anything 
  app:
    # naming the image
    image: analytics-api:v1
    build:
      # context is the current directory, hence '.'
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8002
    env_file:
      - .env
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./app:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
